name: check latest versions
on:
  workflow_dispatch:
  schedule:
    - cron: '13 0 * * *'

jobs:
  check:
    runs-on: ubuntu-20.04
    timeout-minutes: 1

    steps:
      - name: check the latest version of https://github.com/actions/checkout
        uses: ninotosh/check-github-repo-latest-version@v1
        with:
          tag: actions/checkout@v3
          github_token: ${{ secrets.GITHUB_TOKEN }}
